name: choimirai
favicon: null
layout_spectrum: 0.6731913483235985
typography_spectrum: 0.23905618791468441
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.24217267706990242
  lightness: 0.2800207952968776
  saturation: 0.7640440273098648
  rhythmicContrast: 0.3460084388498217
purpose: []
